### ISSUE TITLE
Add distributed tracing?

### ISSUE THREAD

**Issue by jdbohrman** [DickChesterwood/k8s-fleetman#28]
This would be an awesome project to add distributed tracing to with OpenTracing and Jaeger. Maybe you can do a course on it in the future! I can spin up a PR if you'd like! I'll talk through how it works in the PR.

**Comment by DickChesterwood** [comment]
For sure, great idea! I was planning an Istio course, so this is definitely worth adding to the agenda! Plan is to start heavy work on producing this after the holidays, January onwards!

**Comment by jdbohrman** [comment]
I think an Istio course from you would be HYPE! You're a great teacher man. I've enjoyed the course. Are you on Twitter?

**Comment by DickChesterwood** [comment]
Sorry I missed your comment - yes but I rarely post there, must get around to it again. @Richchesterwood.

I'm finally just getting started on the Istio course!
