### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by christomaliyekkal** [DickChesterwood/k8s-fleetman#30]
Example microservices on minikube is taking too much of CPU. I have 16GB Ram 4 Core

(base) k8s-tutorial cmd $ cat /proc/cpuinfo | grep "model name"
model name	: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
model name	: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
model name	: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
model name	: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz

issuing top command says 200+% usage by kube
20   0 3916932  92980  46828 S 207.3  0.6   3:17.59 VBoxHeadless

Is there a way to limit the cpu usage, so that we can get the application running on minikube on laptop?

**Comment by DickChesterwood** [comment]
@christomaliyekkal sorry I didn't see this, I've not been keeping an eye on github repos. 

I do know that the microservices are resource hogs, especially memory. But I developed the system deliberately on a rubbish low powered laptop - much inferior to yours - and it doesn't perform great but it just about passes.

Did you get anywhere with the system/course?

**Comment by DickChesterwood** [comment]
When running, can you try "kubectl top pod", and inspect the output? If you review the chapter in the course on resources and limits, it is possible to limit cpu for a pod, so if there's one particularly pod causing the problem that might be a solution.

**Comment by christomaliyekkal** [comment]
I guess this issues happened only in the early part of the course, where we don't put any limits in the definition. My system used to hang the moment I start both publisher and subscriber. But in later part of the courses, it worked fine, after defining resources and limits. Thank you!
