### ISSUE TITLE
aws k8s cluster: reports are not displaying

### ISSUE THREAD

**Issue by mukeshjoshi04** [DickChesterwood/k8s-fleetman#32]
My deployments:

https://github.com/DickChesterwood/k8s-fleetman/files/3914876/workload_service_storage_mongo-stack.zip

application not working properly

**Comment by mukeshjoshi04** [comment]
My deployments:

[workload_service_storage_mongo-stack.zip](https://github.com/DickChesterwood/k8s-fleetman/files/3914876/workload_service_storage_mongo-stack.zip)

**Comment by RichardKnowles** [comment]
Are you on the course with Udemy, VPP or Manning or just using the files from the repo? It's very likely that there's some critical step on a course video somewhere that's missing. If you are on the course, then can you go to the QA board on the course supplier, we monitor those boards constantly so we should be able to get you up and running quickly.

Needed for full diagnostics:

kubectl get all

Full description of what's happening - if no vehicle reports but the map is rendering, then a copy of the javscript console log.

**Comment by mukeshjoshi04** [comment]
I followed your Udemy course. I also followed your youtube video on google cloud cluster deployment.But output is still same.

**Comment by mukeshjoshi04** [comment]
[logs.zip](https://github.com/DickChesterwood/k8s-fleetman/files/3920336/logs.zip)
I again follow the videos still i dont get any progress
This is the logs of my pods. Please review this.

**Comment by mukeshjoshi04** [comment]
Now I have proceed with the different region . changed from ap-south-1 to us-east-1.
 Now It works perfectly. Any specific reason?

**Comment by mukeshjoshi04** [comment]
Solved: I have checked console log. 
problem we need to update the api: by hitting the url <loadbalancer-IP>/api/update then it worked perfectly.

**Comment by DickChesterwood** [comment]
Thanks for letting me know: I'm not entirely sure what you're doing - just running the system? It shouldn't be necessary to change api urls though, it should just work. 
Where did you make this change? The webapp Javscript code accesses the /api/update url to set up the websocket connection, but it should automatically be "calling back" to the original server, so the loadbalancer ip should be inferred as being the same.

**Comment by mukeshjoshi04** [comment]
In my local system everything works perfectly fine.
In case aws . when we hit load balancer Ip on the browser it only display maps. If you inspect the webpage there is a error as follow:

Error during WebSocket connecttion to {LoadBalanecer IP}: 'Upgrade header is missing
 and a url is there {loadbalancer-IP}/api/update.

After hitting the url reports starts.

**Comment by DickChesterwood** [comment]
Thanks. Are you deploying this to a https domain?

**Comment by mukeshjoshi04** [comment]
No, its http domain.
