### ISSUE TITLE
Install tiller update

### ISSUE THREAD

**Issue by markphip** [DickChesterwood/k8s-fleetman#39]
I am using EKS (which is now using k8s 1.17). When I got to the Helm video the "fix" for Tiller did not work. Reading the Helm docs, I figured out the solution .. need to install Tiller using: `helm init  --service-account tiller`

With that added, your fix script worked perfectly.  I should note I installed the latest Helm 2.x version as opposed to the 3.x version:

```
$ helm version
Client: &version.Version{SemVer:"v2.16.10", GitCommit:"bceca24a91639f045f22ab0f41e47589a932cf5e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.10", GitCommit:"bceca24a91639f045f22ab0f41e47589a932cf5e", GitTreeState:"clean"} 
```

**Comment by DickChesterwood** [comment]
Thanks Mark. Actually I've got a burningly urgent job to rework Helm for this course (jobs piling up!) and remove the Helm 2 and replace with Helm 3 (and move into its own section away from Monitoring), so I'll mop this up at the same time. Thankfully Tiller isn't used in Helm 3.
